spring.application.name=to-do-application
server.port=8080

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://centerbeam.proxy.rlwy.net:35773/railway
spring.datasource.username=postgres
spring.datasource.password=ouQGhkDAoTcFIeEiSqNIAFVkdENrjGIA




spring.datasource.hikari.connection-test-query=SELECT 1
spring.datasource.hikari.validation-timeout=3000
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.initialization-fail-timeout=10000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

#JWT configs
jwt.secret=AbcdEfGhIjKlMnOpQrStUvWxYz1234567890ASDHNSHHahhdnshsjsjsjhdhjherhnsnshdmdhhksjnhdgdhjnbs`
jwt.accessTokenexpiration=360000
jwt.refreshTokenExpiration=604800000
